# -*- coding: utf-8 -*-
"""assistan_id

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e8AB1Grat_i73gi710TkuUAuW1siPEaH
"""

pip install openai --upgrade

import time
import json
import os
import openai

from openai import OpenAI

ASSISTANT_ID = "asst_dO0Ayaa3j4qJTnQEf8AZyGCk"

client = OpenAI(api_key= "sk-proj-")

print(client.beta.assistants.list())

# prompt: print formated list object

assistants = client.beta.assistants.list()
for assistant in assistants.data:
  print(f"ID: {assistant.id}")
  print(f"Name: {assistant.name}")
  print(f"Description: {assistant.description}")
  print("-" * 20)

# prompt: code to open and print a json file

with open('/content/Key_QS.json', 'r') as f:
  json_data = json.load(f)
print(json_data)

thread = client.beta.threads.create(
    messages = [
        {
            "role" : "user",
            "content" : "Can you process this JSON file? Extracts the values from the PDF and populate this JSON file?",
        },
        {
            "role" : "user",
            "content" : f"Here is the attached JSON document : {json_data}",
        }
    ]
)

run = client.beta.threads.runs.create_and_poll(
    thread_id = thread.id,
    assistant_id = ASSISTANT_ID
)
print(f"Run ID: {run.id}")

while run.status != "completed":
    run = client.beta.threads.runs.retrieve(thread_id=thread.id, run_id=run.id)
    print(f"🏃 Run Status: {run.status}")
    time.sleep(1)
else:
    print(f"🏁 Run Completed!")

message_response = client.beta.threads.messages.list(thread_id=thread.id)
messages = message_response.data

# Print the latest message.
latest_message = messages[0]
print(f"💬 Response: {latest_message.content[0].text.value}")

